### ISSUE TITLE
启动成功，但无法访问本地数据，报404错误，要怎么解决？

### ISSUE THREAD

**Issue by hailuo9527** [shenxinshuo/treehole#1]

**Comment by shenxinshuo** [comment]
后端服务是否没起来，404是指前端报404，还是指后端接口报404

**Comment by hailuo9527** [comment]
> 后端服务是否没起来，404是指前端报404，还是指后端接口报404

是后端接口报404，springboot启动成功后访问localhost:8080/treehole无法访问，然后访问后端接口就报404

**Comment by shenxinshuo** [comment]
说明是后端项目问题。springboot启动报错没，路径映射错了没了。看下请求请求服务了没有（控制台有没有打印日志）

**Comment by hailuo9527** [comment]
> 说明是后端项目问题。springboot启动报错没，路径映射错了没了。看下请求请求服务了没有（控制台有没有打印日志）

springboot启动没有报错，路径映射也没错，请求服务控制台没有打印日志

**Comment by shenxinshuo** [comment]
postman能调通吗

**Comment by hailuo9527** [comment]
> postman能调通吗

不能，报404，能加你qq详细说吗

**Comment by shenxinshuo** [comment]
加群：442307195

**Comment by shenxinshuo** [comment]
> 
加群：442307195
